apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: t2ykgci0i-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:b05db4b73abf5e92d599c6a4cab04fd0f475d43c@sha256:853fc4e5ca96c64a43825aab0d08484b24ba23eceaebe753a50c833c2d0aba23
          name: container-image
